routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('index');
});

Route::resource('/banners', 'BannersController');
Auth::routes();

app/Banner.php
<?php

namespace App;

use App\Utils\ArrayUtil;
use Illuminate\Database\Eloquent\Model;

class Banner extends Model {
    public $timestamps = false;
    public $fillable = ['name', 'code', 'priority'];


    /**
     * получить разрешенные приоритеты
     */
    public static function getAllowPriorities ($method) {

        // все приоритеты
        $priorities = array_column(Banner::all('id', 'priority')->sortByDesc('priority')->toArray(), 'priority');


        // если есть приоритеты
        if (count($priorities) > 0) {


            // если создание
            if ($method == 'create') {

                // добавляем еще один приоритет, самый высокий, либо баннер заменит по приоритету другой
                $priorities = array_merge([count($priorities) + 1 => count($priorities) + 1], $priorities);
            }

        } else {

            // если нет ни одного баннера, то доступен только один приоритет
            array_push($priorities, 1);
        }


        // ключи как значения
        $priorities = ArrayUtil::valuesToKeys($priorities);

        // возвращаем приоритеты
        return $priorities;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Api/BannersController.php
<?php

namespace App\Http\Controllers\Api;

use App\Banner;
use App\Http\Controllers\Controller;

/**
 * Created by IntelliJ IDEA.
 * User: vision
 * Date: 03.09.2018
 * Time: 19:28
 */

class BannersController extends Controller {


    public function index () {
        return Banner::all();
    }
}

app/Http/Controllers/BannersController.php
<?php

namespace App\Http\Controllers;

use App;
use App\Banner;
use App\Http\Requests\CreateBannerRequest;
use App\Http\Requests\UpdateBannerRequest;

class BannersController extends Controller {


    public function __construct () {
        $this->middleware('auth');
    }


    public function index () {
        $banners = Banner::all()->sortByDesc('priority');
        return view('banners.index', compact('banners'));
    }


    public function show ($id) {
        $banner = Banner::find($id);
        $priorities = Banner::getAllowPriorities('update');

        return view('banners.edit', compact(['banner', 'priorities']));
    }


    public function create () {
        $priorities = Banner::getAllowPriorities('create');
        return view('banners.create', compact('priorities'));
    }


    public function store (CreateBannerRequest $request) {

        // приоритет баннера
        $priority = $request->get('priority');

        // перестройка приоритетов
        Banner::where('priority', '>=', $priority)->increment('priority', 1);

        // сохраняем
        $banner = new Banner();
        $banner->fill($request->all());
        $banner->save();

        // редиректим на индексную
        return redirect()->route('banners.index');
    }


    public function update ($id, UpdateBannerRequest $request) {

        // находим баннер
        $banner = Banner::findOrFail($id);

        // текущий приоритет баннера
        $currentPriority = $banner->priority;

        // приоритет, который нужно установить баннеру
        $priority = $request->get('priority');

        // если новый приоритет > текущий
        if ($priority > $currentPriority) {

            // все приоритеты от текущего до нового сдвигаются на 1 в сторону меньше
            Banner::where('priority', '<=', $priority)->where('priority', '>', $currentPriority)->decrement('priority', 1);

        } else if ($priority < $currentPriority) {

            // все приоритеты от текущего до нового сдвигаются на 1 в сторону больше
            Banner::where('priority', '>=', $priority)->where('priority', '<', $currentPriority)->increment('priority', 1);

        }

        // сохраняем данные
        $banner->fill($request->all());
        $banner->save();

        // редиректим на главную
        return redirect()->route('banners.index');
    }


    public function destroy ($id) {

        // удаляем данные
        $banner = Banner::findOrFail($id);

        // перестройка приоритетов
        Banner::where('priority', '>', $banner->priority)->decrement('priority', 1);

        // удаляем баннер
        $banner->delete();

        // редиректим на главную
        return redirect()->route('banners.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller {

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct () {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index () {
        return view('home');
    }
}

resources/views/banners/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">

                    <div class="card-header">Добавление рекламного кода</div>

                    @if($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="card-body">
                        {!! Form::open(['route' => ['banners.store'], 'method' => 'POST']) !!}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                {{ Form::label('name', 'Название') }}
                                {{ Form::text('name', '', ['class'=>'form-control']) }}
                            </div>
                            <div class="col-md-6 mb-3">
                                {{ Form::label('priority', 'Приоритет') }}
                                {{ Form::select('priority', $priorities, max(array_keys($priorities)), ['class'=>'form-control']) }}
                            </div>
                        </div>

                        {{ Form::label('code', 'Рекламный JS-код') }}
                        {{ Form::textarea('code', '', ['class'=>'form-control']) }}
                        <div class="modal-footer">
                            <button id="cancel" type="button" data-url="{{ route('banners.index') }}" class="btn btn-danger" href="#">
                                Отмена
                            </button>
                            <button class="btn btn-success" type="submit">Сохранить</button>
                        </div>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>

        $(document).ready(function () {

            $('#cancel').click(function () {
                window.location.href = $(this).data('url');
            });
        });
    </script>

@endsection

resources/views/banners/edit.blade.php
@extends('layouts.app')

@section('content')



    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Изменение рекламного кода</div>

                    @if($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="card-body">
                        {!! Form::open(['route' => ['banners.update', 'id' => $banner->id], 'method' => 'PUT']) !!}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                {{ Form::label('name', 'Название') }}
                                {{ Form::text('name', $banner->name, ['class'=>'form-control']) }}
                            </div>
                            <div class="col-md-6 mb-3">
                                {{ Form::label('priority', 'Приоритет') }}
                                {{ Form::select('priority', $priorities, $banner->priority, ['class'=>'form-control']) }}
                            </div>
                        </div>

                        {{ Form::label('code', 'Рекламный JS-код') }}
                        {{ Form::textarea('code', $banner->code, ['class'=>'form-control']) }}
                        <div class="modal-footer">
                            <button id="cancel" data-url="{{ route('banners.index') }}" class="btn btn-danger" href="#">
                                Отмена
                            </button>
                            <button class="btn btn-success" type="submit">Сохранить</button>
                        </div>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>

        $(document).ready(function () {

            $('#cancel').click(function () {
                window.location.href = $(this).data('url');
            });
        });
    </script>
@endsection

resources/views/banners/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row justify-content-center">

            <div class="col-md-8">

                <div class="card">
                    <div class="card-header" style="display: table; width: 100%">
                        <div style="display: table-cell;">Список рекламных кодов</div>
                        <div style="display: table-cell; text-align: right">
                            {!! Form::open(['route' => ['banners.create'], 'method'=> 'GET']) !!}
                            <button type="submit" class="btn btn-primary">Добавить</button>
                            {!! Form::close() !!}
                        </div>

                    </div>

                    <div class="card-body">
                        @foreach($banners as $banner)

                            <div class="row" style="border-bottom: 1px solid #d8d8d8">
                                <div class="col-md-1 color-blue">{{$banner->priority}}</div>
                                <div class="col-md-7">{{$banner->name}}</div>

                                <div class="col-md-4">
                                    <a class="a-edit color-red removeBanner"
                                       data-token="{{ csrf_token() }}"
                                       data-url="{{ route('banners.destroy', ['id' => $banner->id]) }}"
                                       href="#">Удалить</a>
                                    <a class="a-edit"
                                       href="{{ route('banners.show', ['id' => $banner->id]) }}">Редактировать</a>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>

        $(document).ready(function () {

            /**
             * удалить баннер через ajax
             */
            $('.removeBanner').click(function () {
                var url = $(this).data("url");
                var token = $(this).data("token");

                $.ajax({
                    'url': url,
                    'type': 'POST',
                    'data': { _method: 'delete', _token: token },
                    'success': function () {
                        location.reload();
                    }
                });
            })
        });

    </script>

@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')

    <div id="container">

    </div>

    <input id="route-banner" type="hidden" data-url="{{ route('api.banners.index') }}">


    <script>

        $(document).ready(function () {

            // список баннеров для показа
            var banners = null;


            $.ajax({
                'url': $('#route-banner').data('url'),
                'type': 'GET',
                'success': function (data) {

                    /**
                     * сортировка
                     */
                    function compare(a, b) {
                        if (a.priority > b.priority)
                            return -1;
                        if (a.priority < b.priority)
                            return 1;
                        return 0;
                    }

                    // сортируем по приоритету
                    banners = data.sort(compare);

                    // загружаем баннер для показа
                    loadNextBanner();

                },
                'fail': function () {
                    console.log('ajax load failed');
                }
            });


            /**
             * загружаем следующий баннер
             */
            function loadNextBanner () {

                // если есть баннеры для показа
                if (banners.length > 0) {

                    // удаляем первый элемент и получаем его данные
                    var banner = banners.splice(0, 1)[0];

                    // код для подключения
                    var code = banner['code'];

                    // выполняем код для показа
                    eval(code);

                } else {

                    console.log('banners has not found');
                }
            }
        });

    </script>

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>